import type {
  Arsredovisning,
  Belopprad,
} from "@/model/arsredovisning/Arsredovisning.ts";

export const exampleArsredovisning: Arsredovisning = {
  metadata: {
    taxonomiTyp: "k2",
    taxonomiVersion: "2021-10-31",
  },
  foretagsinformation: {
    foretagsnamn: "Exempelbolaget AB",
    organisationsnummer: "556999-9999",
    adress: "Storgatan 1, 123 45 Exempelstad",
    telefon: "0123-45 67 89",
  },
  verksamhetsarNuvarande: {
    startdatum: "2024-01-01",
    slutdatum: "2024-12-31",
  },
  verksamhetsarTidigare: [
    { startdatum: "2023-01-01", slutdatum: "2023-12-31" },
  ],
  forvaltningsberattelse: [],
  resultatrakning: [
    {
      taxonomyItem: {
        __Level: 1,
        id: "241",
        rowNumber: "2",
        elementnamn: "RorelseresultatAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Rörelseresultat (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "240",
        radrubrik: "Rörelseresultat",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "242",
        rowNumber: "3",
        elementnamn: "RorelsensIntakterLagerforandringarMmAbstract",
        tillhor: "se-gen-base",
        standardrubrik:
          "Rörelseintäkter, lagerförändringar m.m. (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "241",
        radrubrik: "Rörelseintäkter, lagerförändringar m.m.",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "243",
        rowNumber: "4",
        elementnamn: "Nettoomsattning",
        tillhor: "se-gen-base",
        standardrubrik: "Nettoomsättning",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Intäkter från sålda varor och utförda tjänster, primära intäkter, i den normala verksamheten med avdrag för lämnade rabatter, mervärdesskatt och annan skatt som är direkt knuten till omsättningen",
        utokadDokumentation:
          "Primära intäkter i den normala verksamheten, t.ex. varuförsäljning, tjänsteintäkter, hyresintäkter",
        __ParentId: "242",
        radrubrik: "Nettoomsättning",
      },
      beloppNuvarandeAr: "5000",
      beloppForegaendeAr: "3000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "247",
        rowNumber: "8",
        elementnamn: "RorelseintakterLagerforandringarMm",
        tillhor: "se-gen-base",
        standardrubrik: "Rörelseintäkter, lagerförändringar m.m.",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Totala rörelseintäkter som avser den normala verksamheten, enligt en kostnadsslagsindelad uppställningsform för resultaträkning",
        utokadDokumentation:
          "Sammanslagning av följande poster; Nettoomsättning, Förändring av lager av färdiga varor och av varor under tillverkning, inklusive pågående arbeten för annans räkning, Aktiverat arbete för egen räkning och Övriga rörelseintäkter",
        __ParentId: "241",
        radrubrik: "Summa rörelseintäkter, lagerförändringar m.m.",
      },
      beloppNuvarandeAr: "5000",
      beloppForegaendeAr: "3000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "248",
        rowNumber: "9",
        elementnamn: "RorelsekostnaderAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Rörelsekostnader (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "241",
        radrubrik: "Rörelsekostnader",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "251",
        rowNumber: "12",
        elementnamn: "OvrigaExternaKostnader",
        tillhor: "se-gen-base",
        standardrubrik: "Övriga externa kostnader",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Kostnaden för förbrukning av varor och tjänster för primära aktiviteter i den normala verksamheten, andra än kostnader för råvaror och förnödenheter, handelsvaror, personal samt av- och nedskrivningar",
        utokadDokumentation:
          "Alla rörelsekostnader som inte passar i någon annan post t.ex. kontorshyra, konsultarvoden, telefon, porto, reklam och nedskrivningar av kortfristiga fordringar",
        __ParentId: "248",
        radrubrik: "Övriga externa kostnader",
      },
      beloppNuvarandeAr: "150",
      beloppForegaendeAr: "2900",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "252",
        rowNumber: "13",
        elementnamn: "Personalkostnader",
        tillhor: "se-gen-base",
        standardrubrik: "Personalkostnader",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Kostnader som har direkt samband med verksamhetens anställda, t.ex. löner, sociala avgifter, pensionskostnader och företagshälsovård samt dessutom normalt styrelsearvoden. Personalkostnader redovisas brutto",
        __ParentId: "248",
        radrubrik: "Personalkostnader",
      },
      not: 2,
      beloppNuvarandeAr: "1100",
      beloppForegaendeAr: "1100",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "256",
        rowNumber: "17",
        elementnamn: "Rorelsekostnader",
        tillhor: "se-gen-base",
        standardrubrik: "Rörelsekostnader",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Totala rörelsekostnader, både primära och sekundära kostnader, enligt en kostnadsslagsindelad uppställningsform för resultaträkning",
        utokadDokumentation:
          "Sammanslagning av följande poster; Råvaror och förnödenheter, Handelsvaror, Övriga externa kostnader, Personalkostnader, Avskrivningar och nedskrivningar av materiella och immateriella anläggningstillgångar inklusive återföringar av nedskrivningar, Nedskrivningar av omsättningstillgångar utöver normala nedskrivningar och Övriga rörelsekostnader",
        __ParentId: "241",
        radrubrik: "Summa rörelsekostnader",
      },
      beloppNuvarandeAr: "1250",
      beloppForegaendeAr: "4000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "257",
        rowNumber: "18",
        elementnamn: "Rorelseresultat",
        tillhor: "se-gen-base",
        standardrubrik: "Rörelseresultat",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Rörelseintäkter med avdrag för rörelsens kostnader, dvs. resultat utan hänsyn tagen till finansiella poster, bokslutsdispositioner eller skatter. Sammanslagning av rörelseposter beroende på vilken uppställningsform som tillämpas för resultaträkningen",
        __ParentId: "240",
        radrubrik: "Rörelseresultat",
      },
      beloppNuvarandeAr: "3750",
      beloppForegaendeAr: "-1000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "267",
        rowNumber: "28",
        elementnamn: "ResultatEfterFinansiellaPoster",
        tillhor: "se-gen-base",
        standardrubrik: "Resultat efter finansiella poster",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "duration",
        typ: "item",
        dokumentation: "Resultat före bokslutsdispositioner och skatt",
        __ParentId: "240",
        radrubrik: "Resultat efter finansiella poster",
      },
      beloppNuvarandeAr: "3750",
      beloppForegaendeAr: "-1000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "275",
        rowNumber: "36",
        elementnamn: "ResultatForeSkatt",
        tillhor: "se-gen-base",
        standardrubrik: "Resultat före skatt",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Resultat efter finansiella poster och bokslutsdispositioner",
        __ParentId: "240",
        radrubrik: "Resultat före skatt",
      },
      beloppNuvarandeAr: "3750",
      beloppForegaendeAr: "-1000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "276",
        rowNumber: "37",
        elementnamn: "SkatterAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Skatter (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "240",
        radrubrik: "Skatter",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "277",
        rowNumber: "38",
        elementnamn: "SkattAretsResultat",
        tillhor: "se-gen-base",
        standardrubrik: "Skatt på periodens resultat",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "duration",
        typ: "item",
        dokumentation: "Inkomstskatt som belastat periodens resultat",
        __ParentId: "276",
        radrubrik: "Skatt på årets resultat",
      },
      beloppNuvarandeAr: "772",
      beloppForegaendeAr: "0",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "279",
        rowNumber: "40",
        elementnamn: "AretsResultat",
        tillhor: "se-gen-base",
        standardrubrik: "Periodens resultat",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "duration",
        typ: "item",
        dokumentation:
          "Periodens redovisade intäkter med avdrag för periodens redovisade kostnader; över- eller underskott",
        __ParentId: "240",
        radrubrik: "Årets resultat",
      },
      beloppNuvarandeAr: "2978",
      beloppForegaendeAr: "-1000",
    } as Belopprad<"xbrli:monetaryItemType">,
  ],
  balansrakning: [
    {
      taxonomyItem: {
        __Level: 1,
        id: "311",
        rowNumber: "2",
        elementnamn: "TillgangarAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Tillgångar (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "310",
        radrubrik: "Tillgångar",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "340",
        rowNumber: "31",
        elementnamn: "OmsattningstillgangarAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Omsättningstillgångar (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "311",
        radrubrik: "Omsättningstillgångar",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "362",
        rowNumber: "53",
        elementnamn: "KassaBankAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Kassa och bank (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "340",
        radrubrik: "Kassa och bank",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 4,
        id: "363",
        rowNumber: "54",
        elementnamn: "KassaBankExklRedovisningsmedel",
        tillhor: "se-gen-base",
        standardrubrik: "Kassa och bank exklusive redovisningsmedel",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "instant",
        typ: "item",
        dokumentation: "Kontantkassa samt bank- och girotillgodohavanden",
        __ParentId: "362",
        radrubrik: "Kassa och bank",
      },
      beloppNuvarandeAr: "39728",
      beloppForegaendeAr: "36500",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "365",
        rowNumber: "56",
        elementnamn: "KassaBank",
        tillhor: "se-gen-base",
        standardrubrik: "Kassa och bank",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Kontantkassa samt bank- och girotillgodohavanden inklusive redovisningsmedel",
        __ParentId: "340",
        radrubrik: "Summa kassa och bank",
      },
      beloppNuvarandeAr: "39728",
      beloppForegaendeAr: "36500",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "366",
        rowNumber: "57",
        elementnamn: "Omsattningstillgangar",
        tillhor: "se-gen-base",
        standardrubrik: "Omsättningstillgångar",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Andra tillgångar än anläggningstillgångar, dvs. tillgångar som inte är avsedda att stadigvarande brukas eller innehas i verksamheten",
        utokadDokumentation:
          "Tillgångar som avses att omsättas i den normala verksamheten, fordringar som ska betalas inom 12 månader från balansdagen, placeringar som är avsedda att realiseras inom 12 månader eller tillgångar som utgörs av likvida medel",
        __ParentId: "311",
        radrubrik: "Summa omsättningstillgångar",
      },
      beloppNuvarandeAr: "39728",
      beloppForegaendeAr: "36500",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "367",
        rowNumber: "58",
        elementnamn: "Tillgangar",
        tillhor: "se-gen-base",
        standardrubrik: "Tillgångar",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "debit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Totala tillgångar i en verksamhet (balansomslutning); anläggningstillgångar och omsättningstillgångar",
        utokadDokumentation:
          "Består av; Tecknat men ej inbetalt kapital, Immateriella anläggningstillgångar, Materiella anläggningstillgångar, Finansiella anläggningstillgångar, Varulager, Kortfristiga fordringar, Kortfristiga placeringar och Kassa och bank",
        __ParentId: "310",
        radrubrik: "Summa tillgångar",
      },
      beloppNuvarandeAr: "39728",
      beloppForegaendeAr: "36500",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "368",
        rowNumber: "59",
        elementnamn: "EgetKapitalSkulderAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Eget kapital och skulder (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "310",
        radrubrik: "Eget kapital och skulder",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "369",
        rowNumber: "60",
        elementnamn: "EgetKapitalAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Eget kapital (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "368",
        radrubrik: "Eget kapital",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "370",
        rowNumber: "61",
        elementnamn: "BundetEgetKapitalAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Bundet eget kapital (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "369",
        radrubrik: "Bundet eget kapital",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 4,
        id: "371",
        rowNumber: "62",
        elementnamn: "Aktiekapital",
        tillhor: "se-gen-base",
        standardrubrik: "Aktiekapital",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Registrerat kapital hos Bolagsverket, enligt aktiebolagslagen",
        __ParentId: "370",
        radrubrik: "Aktiekapital",
      },
      beloppNuvarandeAr: "25000",
      beloppForegaendeAr: "25000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "377",
        rowNumber: "68",
        elementnamn: "FrittEgetKapitalAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Fritt eget kapital (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "369",
        radrubrik: "Fritt eget kapital",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 4,
        id: "379",
        rowNumber: "70",
        elementnamn: "BalanseratResultat",
        tillhor: "se-gen-base",
        standardrubrik: "Balanserat resultat",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Det sammanlagda beloppet av tidigare års balanserade vinster eller förluster",
        utokadDokumentation:
          "Det sammanlagda beloppet av tidigare års balanserade vinster, förluster och fria överkursfonder samt aktieägartillskott",
        __ParentId: "377",
        radrubrik: "Balanserat resultat",
      },
      beloppNuvarandeAr: "11000",
      beloppForegaendeAr: "12000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 4,
        id: "380",
        rowNumber: "71",
        elementnamn: "AretsResultatEgetKapital",
        tillhor: "se-gen-base",
        standardrubrik: "Periodens resultat i eget kapital",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Periodens över- eller underskott i eget kapital, dvs. periodens redovisade intäkter med avdrag för periodens redovisade kostnader",
        __ParentId: "377",
        radrubrik: "Årets resultat",
      },
      beloppNuvarandeAr: "2978",
      beloppForegaendeAr: "-1000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "381",
        rowNumber: "72",
        elementnamn: "FrittEgetKapital",
        tillhor: "se-gen-base",
        standardrubrik: "Fritt eget kapital",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Del av ägarkapitalet som är fritt, innebär att det kan användas för utbetalningar till aktieägarna eller medlemmarna; dvs. utdelningsbart kapital, även kallat disponibla medel",
        utokadDokumentation:
          "Sammanslagning av följande poster; Fri överkursfond, Balanserat resultat och Periodens resultat",
        __ParentId: "369",
        radrubrik: "Summa fritt eget kapital",
      },
      beloppNuvarandeAr: "13978",
      beloppForegaendeAr: "11000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "382",
        rowNumber: "73",
        elementnamn: "EgetKapital",
        tillhor: "se-gen-base",
        standardrubrik: "Eget kapital",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Skillnad mellan redovisade tillgångar och redovisade skulder; totalt ägarkapital",
        utokadDokumentation: "Sammanslagning av bundet och fritt eget kapital",
        __ParentId: "368",
        radrubrik: "Summa eget kapital",
      },
      beloppNuvarandeAr: "38978",
      beloppForegaendeAr: "36000",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 2,
        id: "402",
        rowNumber: "93",
        elementnamn: "KortfristigaSkulderAbstract",
        tillhor: "se-gen-base",
        standardrubrik: "Kortfristiga skulder (Presentation)",
        abstrakt: "true",
        datatyp: "xbrli:stringItemType",
        periodtyp: "duration",
        typ: "item",
        __ParentId: "368",
        radrubrik: "Kortfristiga skulder",
      },
    } as Belopprad<"xbrli:stringItemType">,
    {
      taxonomyItem: {
        __Level: 3,
        id: "414",
        rowNumber: "105",
        elementnamn: "OvrigaKortfristigaSkulder",
        tillhor: "se-gen-base",
        standardrubrik: "Övriga kortfristiga skulder",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Övriga kortfristiga skulder, t.ex. mervärdesskatt, punktskatter, lagstadgade arbetsgivaravgifter som förfaller till betalning efterföljande månad, innehållen personalskatt och redovisningsmedel",
        __ParentId: "402",
        radrubrik: "Övriga skulder",
      },
      beloppNuvarandeAr: "750",
      beloppForegaendeAr: "500",
    } as Belopprad<"xbrli:monetaryItemType">,
    {
      taxonomyItem: {
        __Level: 1,
        id: "417",
        rowNumber: "108",
        elementnamn: "EgetKapitalSkulder",
        tillhor: "se-gen-base",
        standardrubrik: "Eget kapital och skulder",
        abstrakt: "false",
        datatyp: "xbrli:monetaryItemType",
        saldo: "credit",
        periodtyp: "instant",
        typ: "item",
        dokumentation:
          "Totala skulder inklusive eget kapital i en verksamhet (balansomslutning); eget kapital, obeskattade reserver, avsättningar, långfristiga och kortfristiga skulder",
        utokadDokumentation:
          "Sammanslagning av följande poster; Eget kapital, Avsättningar, Obeskattade reserver, Långfristiga skulder och Kortfristiga skulder",
        __ParentId: "310",
        radrubrik: "Summa eget kapital och skulder",
      },
      beloppNuvarandeAr: "39728",
      beloppForegaendeAr: "36500",
    } as Belopprad<"xbrli:monetaryItemType">,
  ],
  noter: [],
};
