---
openapi: 3.1.0
components:
  schemas:
    Handlingsinfo:
      type: object
      properties:
        typ:
          $ref: "#/components/schemas/TypEnum1"
        dokumentlangd:
          type: integer
          format: int32
        idnummer:
          type: string
        sha256checksumma:
          type: string
          format: binary
    InlamningOK:
      type: object
      properties:
        orgnr:
          type: string
        avsandare:
          type: string
        undertecknare:
          type: string
        handlingsinfo:
          $ref: "#/components/schemas/Handlingsinfo"
        url:
          type: string
    KontrolleraSvar:
      type: object
      properties:
        orgnr:
          type: string
        utfall:
          type: array
          items:
            $ref: "#/components/schemas/KontrolleraUtfall"
    KontrolleraUtfall:
      type: object
      properties:
        kod:
          type: string
        text:
          type: string
        typ:
          $ref: "#/components/schemas/TypEnum"
        tekniskinformation:
          type: array
          items:
            $ref: "#/components/schemas/KontrolleraUtfallTekniskInformation"
    KontrolleraUtfallTekniskInformation:
      type: object
      properties:
        meddelande:
          type: string
        element:
          type: string
        varde:
          type: string
    KravPaRevisionsberattelseEnum:
      type: string
      enum:
      - ja
      - nej
      - uppgift_saknas
    LocalDate:
      type: string
      format: date
      examples:
      - 2022-03-10
    PreparationRequest:
      type: object
      required:
      - companyOrgnr
      - signerPnr
      - signedPdf
      properties:
        companyOrgnr:
          type: string
        signerPnr:
          type: string
        signedPdf:
          type: string
          format: binary
    Rakenskapsperiod:
      type: object
      properties:
        from:
          $ref: "#/components/schemas/LocalDate"
        tom:
          $ref: "#/components/schemas/LocalDate"
        kravPaRevisionsberattelse:
          $ref: "#/components/schemas/KravPaRevisionsberattelseEnum"
        revisorsplikt:
          $ref: "#/components/schemas/RevisorspliktEnum"
    RecordsResponse:
      type: object
      required:
      - foretagsnamn
      - rakenskapsperioder
      properties:
        foretagsnamn:
          type: string
        rakenskapsperioder:
          type: array
          items:
            $ref: "#/components/schemas/Rakenskapsperiod"
    RevisorspliktEnum:
      type: string
      enum:
      - ja
      - nej
      - uppgift_saknas
    SkapaTokenOK:
      type: object
      properties:
        token:
          $ref: "#/components/schemas/UUID"
        avtalstext:
          type: string
        avtalstextAndrad:
          $ref: "#/components/schemas/LocalDate"
    SubmissionRequest:
      type: object
      required:
      - companyOrgnr
      - signerPnr
      - signedPdf
      - ixbrl
      - notificationEmail
      properties:
        companyOrgnr:
          type: string
        signerPnr:
          type: string
        signedPdf:
          type: string
          format: binary
        ixbrl:
          type: string
          format: binary
        notificationEmail:
          type: string
    TypEnum:
      type: string
      enum:
      - info
      - warn
      - error
    TypEnum1:
      type: string
      enum:
      - arsredovisning_komplett
      - arsredovisning_kompletteras
      - revisionsberattelse
    UUID:
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
    ValidationRequest:
      type: object
      required:
      - companyOrgnr
      - signerPnr
      - signedPdf
      - ixbrl
      properties:
        companyOrgnr:
          type: string
        signerPnr:
          type: string
        signedPdf:
          type: string
          format: binary
        ixbrl:
          type: string
          format: binary
paths:
  /v1/information/records/{orgnr}:
    get:
      parameters:
      - name: orgnr
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecordsResponse"
      summary: Records
      tags:
      - Information Resource
  /v1/submission-flow/prepare:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PreparationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SkapaTokenOK"
        "400":
          description: Bad Request
      summary: Prepare
      tags:
      - Submission Flow Resource
  /v1/submission-flow/submit:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmissionRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InlamningOK"
        "400":
          description: Bad Request
      summary: Submit
      tags:
      - Submission Flow Resource
  /v1/submission-flow/validate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValidationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KontrolleraSvar"
        "400":
          description: Bad Request
      summary: Validate
      tags:
      - Submission Flow Resource
servers:
- url: http://localhost:8080
- url: https://api.acc.test.gredor.se
- url: https://api.gredor.se
info:
  title: gredor-backend API
  version: 1.0-SNAPSHOT
