---
openapi: 3.1.0
components:
  schemas:
    AuthInitRequest:
      type: object
      required:
      - personalNumber
      properties:
        personalNumber:
          type: string
          pattern: "^\\d{12}$"
    AuthStatus:
      type: string
      enum:
      - PENDING
      - COMPLETE
      - FAILED
    AuthStatusRequest:
      type: object
      required:
      - orderRef
      properties:
        orderRef:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    BankIdStatusResponse:
      type: object
      required:
      - status
      properties:
        orderRef:
          type:
          - string
          - "null"
        autoStartToken:
          type:
          - string
          - "null"
        status:
          $ref: "#/components/schemas/AuthStatus"
        statusPendingData:
          anyOf:
          - $ref: "#/components/schemas/StatusPendingData"
          - type: "null"
        statusCompleteData:
          anyOf:
          - $ref: "#/components/schemas/StatusCompleteData"
          - type: "null"
        statusFailedData:
          anyOf:
          - $ref: "#/components/schemas/StatusFailedData"
          - type: "null"
    CancelRequest:
      type: object
      required:
      - orderRef
      properties:
        orderRef:
          type: string
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    Handlingsinfo:
      type: object
      properties:
        typ:
          $ref: "#/components/schemas/TypEnum1"
        dokumentlangd:
          type: integer
          format: int32
        idnummer:
          type: string
        sha256checksumma:
          type: string
          format: binary
    InlamningOK:
      type: object
      properties:
        orgnr:
          type: string
        avsandare:
          type: string
        undertecknare:
          type: string
        handlingsinfo:
          $ref: "#/components/schemas/Handlingsinfo"
        url:
          type: string
    KontrolleraSvar:
      type: object
      properties:
        orgnr:
          type: string
        utfall:
          type: array
          items:
            $ref: "#/components/schemas/KontrolleraUtfall"
    KontrolleraUtfall:
      type: object
      properties:
        kod:
          type: string
        text:
          type: string
        typ:
          $ref: "#/components/schemas/TypEnum"
        tekniskinformation:
          type: array
          items:
            $ref: "#/components/schemas/KontrolleraUtfallTekniskInformation"
    KontrolleraUtfallTekniskInformation:
      type: object
      properties:
        meddelande:
          type: string
        element:
          type: string
        varde:
          type: string
    KravPaRevisionsberattelseEnum:
      type: string
      enum:
      - ja
      - nej
      - uppgift_saknas
    LocalDate:
      type: string
      format: date
      examples:
      - 2022-03-10
    PreparationRequest:
      type: object
      required:
      - foretagOrgnr
      properties:
        foretagOrgnr:
          type: string
          pattern: "^\\d{10}$"
    PreparationResponse:
      type: object
      required:
      - avtalstext
      - avtalstextAndrad
      properties:
        avtalstext:
          type: string
        avtalstextAndrad:
          $ref: "#/components/schemas/LocalDate"
    Rakenskapsperiod:
      type: object
      properties:
        from:
          $ref: "#/components/schemas/LocalDate"
        tom:
          $ref: "#/components/schemas/LocalDate"
        kravPaRevisionsberattelse:
          $ref: "#/components/schemas/KravPaRevisionsberattelseEnum"
        revisorsplikt:
          $ref: "#/components/schemas/RevisorspliktEnum"
    RecordsResponse:
      type: object
      required:
      - foretagsnamn
      - rakenskapsperioder
      properties:
        foretagsnamn:
          type: string
        rakenskapsperioder:
          type: array
          items:
            $ref: "#/components/schemas/Rakenskapsperiod"
    RevisorspliktEnum:
      type: string
      enum:
      - ja
      - nej
      - uppgift_saknas
    StatusCompleteData:
      type: object
      required:
      - personalNumber
      - token
      properties:
        personalNumber:
          type: string
        token:
          type: string
    StatusFailedData:
      type: object
      properties:
        hintCode:
          type:
          - string
          - "null"
    StatusPendingData:
      type: object
      required:
      - qrCodeImageBase64
      properties:
        qrCodeImageBase64:
          type: string
        hintCode:
          type:
          - string
          - "null"
    SubmissionRequest:
      type: object
      required:
      - foretagOrgnr
      - ixbrl
      - aviseringEpost
      properties:
        foretagOrgnr:
          type: string
          pattern: "^\\d{10}$"
        ixbrl:
          type: string
          format: binary
        aviseringEpost:
          type: string
    TypEnum:
      type: string
      enum:
      - info
      - warn
      - error
    TypEnum1:
      type: string
      enum:
      - arsredovisning_komplett
      - arsredovisning_kompletteras
      - revisionsberattelse
    ValidationRequest:
      type: object
      required:
      - foretagOrgnr
      - ixbrl
      properties:
        foretagOrgnr:
          type: string
          pattern: "^\\d{10}$"
        ixbrl:
          type: string
          format: binary
paths:
  /v1/bankid/cancel:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CancelRequest"
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Cancel
      tags:
      - Bank Id Resource
  /v1/bankid/init:
    post:
      parameters:
      - name: personalNumber
        in: cookie
        schema:
          type:
          - string
          - "null"
      - name: token
        in: cookie
        schema:
          type:
          - string
          - "null"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthInitRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankIdStatusResponse"
        "400":
          description: Bad Request
      summary: Auth Init
      tags:
      - Bank Id Resource
  /v1/bankid/status:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthStatusRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankIdStatusResponse"
        "400":
          description: Bad Request
      summary: Auth Status
      tags:
      - Bank Id Resource
  /v1/information/records/{orgnr}:
    get:
      parameters:
      - name: orgnr
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecordsResponse"
      summary: Records
      tags:
      - Information Resource
  /v1/submission-flow/prepare:
    post:
      parameters:
      - name: personalNumber
        in: cookie
        schema:
          type:
          - string
          - "null"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PreparationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PreparationResponse"
        "400":
          description: Bad Request
      summary: Prepare
      tags:
      - Submission Flow Resource
  /v1/submission-flow/submit:
    post:
      parameters:
      - name: personalNumber
        in: cookie
        schema:
          type:
          - string
          - "null"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmissionRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InlamningOK"
        "400":
          description: Bad Request
      summary: Submit
      tags:
      - Submission Flow Resource
  /v1/submission-flow/validate:
    post:
      parameters:
      - name: personalNumber
        in: cookie
        schema:
          type:
          - string
          - "null"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValidationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KontrolleraSvar"
        "400":
          description: Bad Request
      summary: Validate
      tags:
      - Submission Flow Resource
servers:
- url: http://localhost:8080
- url: https://api.acc.test.gredor.se
- url: https://api.gredor.se
info:
  title: gredor-backend API
  version: 1.0-SNAPSHOT
